package edu.uba.filters.Schema;

import org.jsefa.Deserializer;
import org.jsefa.Deserializer.*;
import org.jsefa.csv.*;

public class Definition {
    public Integer record_ID;
    public Double target_purchase;
    public String C2;
    public Integer C3;
    public String C4;
    public String C5;
    public String C6;
    public Double C7;
    public Double C8;
    public Double C9;
    public Double C10;
    public String C11;
    public Double C12;
    public String C13;
    public Double C14;
    public String C15;
    public String C16;
    public String C17;
    public Double C18;
    public String C19;
    public String C20;
    public String C21;
    public String C22;
    public Double C23;
    public Double C24;
    public Double C25;
    public Double C26;
    public Double C27;
    public String C28;
    public Double C29;
    public String C30;
    public Double C31;
    public Double C32;
    public Double C33;
    public Double C34;
    public Double C35;
    public Double C36;
    public Double C37;
    public Double C38;
    public Double C39;
    public Double C40;
    public Double C41;
    public Double C42;
    public Double C43;
    public Double C44;
    public Double C45;
    public Double C46;
    public Double C47;
    public Double C48;
    public Double C49;
    public Double C50;
    public Double C51;
    public Double C52;
    public String C53;
    public Double C54;
    public Double C55;
    public Double C56;
    public Double C57;
    public Double C58;
    public Double C59;
    public String C60;
    public Double C61;
    public Double C62;
    public Double C63;
    public Double C64;
    public Double C65;
    public Double C66;
    public Double C67;
    public Double C68;
    public Double C69;
    public Double C70;
    public Double C71;
    public Double C72;
    public Double C73;
}
